### ISSUE TITLE
Badge跑偏了

### ISSUE THREAD

**Issue by QueenieMar** [ladybirdDEV/ui-nuclear-mobile#131]
![image](https://user-images.githubusercontent.com/19548158/42018782-b7140562-7ae5-11e8-8796-9f518a9a6d46.png)

**Comment by tortorse** [comment]
需要在外部额外配置一个样式来设定list-item的样式

**Comment by tortorse** [comment]
![image](https://user-images.githubusercontent.com/10540493/42019182-0d5a04fc-7ae7-11e8-8459-d2c51e8273e3.png)

```css
.special-badge .am-list-line {
  padding-right: 0;
}
.special-badge .am-list-line .am-list-extra {
  padding: 0;
  height: 44px;
}
.special-badge .am-badge {
  transform: rotate(45deg);
  transform-origin: right bottom;
  right: 0;
  top: 13px;
  width: 50px;
}
.special-badge .am-badge-text {
  border-radius: 1px;
}
```
